### PR TITLE
Add common device.mk

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by feherneoh** [comment]
you are doing it wrong

**Comment by ghost** [comment]
Have you viewed the PR? If yes, then tell me what's wrong? Or shouldn't I do anything?

**Comment by r3pwn** [comment]
We're moving only the common parts from the devices into here, so there should be no ifeqs for any specific device.

**Comment by ghost** [comment]
Sorry, I often write before thinking.

**Pull request closed without merging**
